# Generated by Django 5.2.14 on 2026-05-25 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField()),
                ('row_number', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSED', 'PROCESSED'), ('FAILED', 'FAILED')], default='PENDING', max_length=50)),
                ('parse_errors', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.datasource')),
            ],
        ),
    ]
