# Generated by Django 5.2.14 on 2026-05-25 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0002_rawrecord'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SCOPE1', 'SCOPE1'), ('SCOPE2', 'SCOPE2'), ('SCOPE3', 'SCOPE3')], max_length=20)),
                ('activity_type', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('normalized_unit', models.CharField(max_length=50)),
                ('emission_factor', models.FloatField()),
                ('co2e', models.FloatField()),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='organizations.organization')),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='ingestion.rawrecord')),
            ],
        ),
    ]
